fix:handling music generation error
leleuvilela/leniser-wpp pull request #58
Opened 2024-08-09 15:28 UTC by LucasMGS

2024-08-10 23:47 UTC, tuliopaim requested changes

2024-08-10 23:47 UTC, tuliopaim commented on src/application/events/music.ts
> +                    `${defaultMemberConfigs.botPrefix} Algo deu errado. Tenta denovo com um prompt menos específico.`
Tenta novamente* fica mais elegante

2024-08-10 23:47 UTC, tuliopaim commented on src/infrastructure/services/musicService.ts
> +                throw new Error(JSON.stringify(response.data));
loga o erro apenas ao invés de disparar uma exception

2024-08-11 11:50 UTC, leleuvilela commented on src/application/events/music.ts
> +                    `${defaultMemberConfigs.botPrefix} Algo deu errado. Tenta denovo com um prompt menos específico.`
Tente* novvamente

2024-08-11 11:52 UTC, leleuvilela commented on src/infrastructure/services/musicService.ts
> +                throw new Error(JSON.stringify(response.data));
e não se usa stringify em error, podemos querer analisar esse erro depois em outro lugar e vamos preferir o objeto.

2024-08-12 14:18 UTC, tuliopaim approved these changes

2024-08-12 14:19 UTC, merged